# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - cache-{{.Environment.CIRCLE_JOB}}-{{ checksum "setup.py" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .[dev]

      - save_cache:
          paths:
            - ./venv
          key: cache-{{.Environment.CIRCLE_JOB}}-{{ checksum "setup.py" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir test-reports
            pytest tests --junitxml=test-reports/junit.xml
            mypy --follow-imports=silent --ignore-missing-imports --no-strict-optional --check-untyped-defs --disallow-incomplete-defs -p beacon_chain.state

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports